devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common:
        device_cgroup_rules: '[ "c 199:* rmw" , "c 226:* rmw" ]'
    debug: {}
    release: {}
id: 3a6bf5fe-28e7-499b-8834-afd83f72af21
images:
    debug: sha256:b6eee4e21d04d03824cdbc8eccc0c16c76f1b94a48d5e5520a287e1e38fecd37
    release: sha256:bfdec806e7580b52f69f74f0c6327d69aea8b9d669bccaf4b377faf0d8db012d
imagetags:
    debug: sdl2-learning_arm32v7-wayland-base-no-ssh_bullseye_debug_3a6bf5fe-28e7-499b-8834-afd83f72af21
    release: sdl2-learning_arm32v7-wayland-base-no-ssh_bullseye_release_3a6bf5fe-28e7-499b-8834-afd83f72af21
modificationdate: '2022-02-01T23:09:04.666135'
networks:
    common: []
    debug: []
    release: []
otapackagename: tic-tac-toe
otapackageversion: 0.2.0-arm32v7
platformid: arm32v7-wayland-base-no-ssh_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEpAIBAAKCAQEA2+0mClc2rR7ec41Au3zHFsDft4H7T+nReBOVsg5zaZTCWWOf

    wFQUdarz3eMrvIRUxRDD2vttCrywZba08i3UZBfs4ZK6mE8ju53h5Sl9q37Yezz3

    V+rtQ5mceeEgSyOF4beMINKOeLnDZHxycIFNrArYmksC8ZUBjK18VSUezRisNk6y

    vPqUIs7z4nXhpKog3U2nPwLcca0LlpCwKkjkNol2YrO8lfiR/0vwC7QagtP9FPvn

    NeKq6ZZHBLCK2vYAwkNeb0rm3NcOmcm2nqAexVUPCWyQU95ltgr4BTTdQVaPYs6d

    VtUn6mMUl8gA2P0IM/YjJtg1zK+Xd9eiziBFEQIDAQABAoIBAQCww7xWhWCx5uS/

    FWJZD2JpfF6T/UpEIde13m/sLEdBLkrDVBp7mFjVdrEJv+RQYkBMIDx7TqiG/7/8

    EM0A9isGxGAlsix97OX4j16YNTAH3i0baJYZOP643cdyAqtVGVkrYb6kRvgyOoS8

    yHWmzZbjV9hesznLeItFSc9sFCjciKCzU5K4HHqIIG/tYdsNkjzaSb+cS2smNvCc

    K1XL1ZvIaW68qZ6iXNkWbVrhMSUiRFtJO4E0CBZL/PuwKqC5b0BhVNhpmBReeR8r

    nWoV0KPWKyGKTDpG7rzWd450pSU3LLrSHkgGtNrmk0NbyT9eYgMM9hVHuypbVSte

    P/UQYurRAoGBAP9qVOirpQynw9x/JsFYexDOHTWcXAbpR9biMovrjplKtsCMZxix

    e34APYGma4niVZCaMjPi6qatIQXpQJ8pNA9uNf/OrzNQiMcc3nMZGaFR78oXTCYJ

    fHS5IiojnfunUooQZHt7gMFK8lbO2rUN/J41D0ENw9Fy3IgAizeB8J6VAoGBANxu

    BWUPJ+aHhiBp7y7XapI9yK3A08W0oWrKdiZtJLzvu/03H4w6tRPdHywjALaYlZG2

    ylSFw5cZj9rIwetBtK0CNDs63KaECBzI1YWIodk/SDU+9tXOrmFiSXDOehseOOhA

    DZPwsxwCmRWehoLpc9T0WuUVOTh3tLsNAQtEcvmNAoGBAIbhbz+DzWB2g+9AUoYO

    JMdGIZS7IrofnWl0AH91gNOg6gua2aLnrzBmDhUWfnnNRaRcWaCe943XpbXKbO7g

    QnbXm7qgOlNd9y03KJ4dpjRT4c6WKQd5QPke/1TDhF1uCh+Q8o9nNCJfYsTG7iZo

    4Xvmx0xyaXOFNcK4jsxcWWZVAoGADrHi+C6/eTXVsjl9sYC44RDvXO368DYvgKAI

    ql0iUtokjSfsmXuccLuQBXA77vBTIEiwSlw0gtE4btxtWRKjSdlYxA4TgaJRrCGT

    YniOWZ5HYQ1WhUBnDaTwwm1xZHdqUclbXl5wglCGBhPwYa/QggTcPmNg0ivgx4uB

    Y0/n3k0CgYB7wFC7Eb7vK1ax4QVITKdO95wPGFlpuUqMc4ZM2Uwfkr8hzDYH0wBJ

    UMTUEvuu5EVCG+L/h5UonN6MCS3c2wje3l+OqwQIbUG3iyLS/mRPVfmj2dJO1vdO

    0zLPwMb7gsni022b0Cf/KV0KudR9JZHetK9Cgtgoy7Zr2/shmtitdw==

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appname: sdl2-learning
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: git cmake ninja-build zip unzip gettext asciidoctor libpng-dev:#%platform.debian-arch%#
            libsdl2-dev:#%platform.debian-arch%# libsdl2-image-dev:#%platform.debian-arch%#
            libsdl2-ttf-dev:#%platform.debian-arch%# libopenal-dev:#%platform.debian-arch%#
            libphysfs-dev:#%platform.debian-arch%# libvorbis-dev:#%platform.debian-arch%#
            libtheora-dev:#%platform.debian-arch%# libxrandr-dev:#%platform.debian-arch%#
            libfribidi-dev:#%platform.debian-arch%# libfreetype6-dev:#%platform.debian-arch%#
            libharfbuzz-dev:#%platform.debian-arch%# libfontconfig1-dev:#%platform.debian-arch%#
            libcurl4-gnutls-dev:#%platform.debian-arch%# gnutls-dev:#%platform.debian-arch%#
            libsodium-dev:#%platform.debian-arch%# libsqlite3-dev:#%platform.debian-arch%#
            libvulkan-dev:#%platform.debian-arch%# libwayland-dev:#%platform.debian-arch%#
            libglew-dev:#%platform.debian-arch%# glslang-dev:#%platform.debian-arch%#
            libglm-dev:#%platform.debian-arch%# gambas3-gb-opengl-glsl:#%platform.debian-arch%#
        env: ENV SDL_VIDEODRIVER="wayland"
        exename: capp
        expose: ''
        extrapackages: libpng16-16 libopenal1 libphysfs1 libvorbis0a libvorbisfile3
            libvorbisidec1 libvorbis-ocaml libtheora0 libtheora-ocaml libtheora-bin
            libxrandr2 libfribidi-bin libfribidi0 libfreetype6 libharfbuzz0b libharfbuzz-bin
            libharfbuzz-gobject0 libharfbuzz-icu0 libfontconfig1 libcurl4 libcurl3-gnutls
            libgnutls30 libgnutlsxx28  libsodium23 libsqlite3-0 libsqlite3-ocaml xdg-utils
            libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0
        language: c-cpp-nossh
        preinstallcommands: ''
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        tag: leograba/tic-tac-toe:0.2.0-arm32v7
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb7SYKVzatHt5zjUC7fMcWwN+3gftP6dF4E5WyDnNplMJZY5/AVBR1qvPd4yu8hFTFEMPa+20KvLBltrTyLdRkF+zhkrqYTyO7neHlKX2rfth7PPdX6u1DmZx54SBLI4Xht4wg0o54ucNkfHJwgU2sCtiaSwLxlQGMrXxVJR7NGKw2TrK8+pQizvPideGkqiDdTac/AtxxrQuWkLAqSOQ2iXZis7yV+JH/S/ALtBqC0/0U++c14qrplkcEsIra9gDCQ15vSubc1w6ZybaeoB7FVQ8JbJBT3mW2CvgFNN1BVo9izp1W1SfqYxSXyADY/Qgz9iMm2DXMr5d316LOIEUR
sdkimages:
    debug: sha256:d218789d764b616d0dcba4680a63e443e2f82527846683d73980aa48661fb74c
    release: sha256:a682608bfae3630465dd00e303917cf40d803c700edffaff966dc25191a9a47d
sdkimagetags:
    debug: sdl2-learning_arm32v7-wayland-base-no-ssh_bullseye_debug_3a6bf5fe-28e7-499b-8834-afd83f72af21_sdk_image
    release: sdl2-learning_arm32v7-wayland-base-no-ssh_bullseye_release_3a6bf5fe-28e7-499b-8834-afd83f72af21_sdk_image
sdksshaddress:
    debug: null
    release: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common:
        /dev/dri: /dev/dri
        /tmp: /tmp
    debug:
        /home/torizon/sdl2-learning: /sdl2-learning,rw
    release: {}
