services:
  tic-tac-toe:
    depends_on:
    - weston
    device_cgroup_rules:
    - c 199:* rmw
    - c 226:* rmw
    image: leograba/tic-tac-toe:0.1.0-arm32v7
    volumes:
    - /tmp:/tmp:rw
    - /dev/dri:/dev/dri:rw
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 226:* rmw
    image: torizon/weston:2.5
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '2.4'